server:
  error:
    path: /error
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:4306/uopp
    password: root
  mail:
    host: localhost
    username: phello
    password: uhello
    port: '4025'
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
jwt:
  secret: 'test-secret'
app:
  frontend-url: "http://localhost:3000"
fc:
  opportunity:
    url: 'http://localhost:5000'
